
#ifndef SDLI_H
#define SDLI_H

#include <SDL.h>

typedef int32_t INPUT_VAL;

#define INPUT_KEYS( f ) f( INPUT_KEY_BACKSPACE, SDLK_BACKSPACE ) f( INPUT_KEY_TAB, SDLK_TAB ) f( INPUT_KEY_RETURN, SDLK_RETURN ) f( INPUT_KEY_PAUSE, SDLK_PAUSE ) f( INPUT_KEY_ESCAPE, SDLK_ESCAPE ) f( INPUT_KEY_SPACE, SDLK_SPACE ) f( INPUT_KEY_EXCLAIM, SDLK_EXCLAIM ) f( INPUT_KEY_QUOTEDBL, SDLK_QUOTEDBL ) f( INPUT_KEY_HASH, SDLK_HASH ) f( INPUT_KEY_DOLLAR, SDLK_DOLLAR ) f( INPUT_KEY_AMPERSAND, SDLK_AMPERSAND ) f( INPUT_KEY_QUOTE, SDLK_QUOTE ) f( INPUT_KEY_LEFTPAREN, SDLK_LEFTPAREN ) f( INPUT_KEY_RIGHTPAREN, SDLK_RIGHTPAREN ) f( INPUT_KEY_ASTERISK, SDLK_ASTERISK ) f( INPUT_KEY_PLUS, SDLK_PLUS ) f( INPUT_KEY_COMMA, SDLK_COMMA ) f( INPUT_KEY_MINUS, SDLK_MINUS ) f( INPUT_KEY_PERIOD, SDLK_PERIOD ) f( INPUT_KEY_SLASH, SDLK_SLASH ) f( INPUT_KEY_0, SDLK_0 ) f( INPUT_KEY_1, SDLK_1 ) f( INPUT_KEY_2, SDLK_2 ) f( INPUT_KEY_3, SDLK_3 ) f( INPUT_KEY_4, SDLK_4 ) f( INPUT_KEY_5, SDLK_5 ) f( INPUT_KEY_6, SDLK_6 ) f( INPUT_KEY_7, SDLK_7 ) f( INPUT_KEY_8, SDLK_8 ) f( INPUT_KEY_9, SDLK_9 ) f( INPUT_KEY_COLON, SDLK_COLON ) f( INPUT_KEY_SEMICOLON, SDLK_SEMICOLON ) f( INPUT_KEY_LESS, SDLK_LESS ) f( INPUT_KEY_EQUALS, SDLK_EQUALS ) f( INPUT_KEY_GREATER, SDLK_GREATER ) f( INPUT_KEY_QUESTION, SDLK_QUESTION ) f( INPUT_KEY_AT, SDLK_AT ) f( INPUT_KEY_LEFTBRACKET, SDLK_LEFTBRACKET ) f( INPUT_KEY_BACKSLASH, SDLK_BACKSLASH ) f( INPUT_KEY_RIGHTBRACKET, SDLK_RIGHTBRACKET ) f( INPUT_KEY_CARET, SDLK_CARET ) f( INPUT_KEY_UNDERSCORE, SDLK_UNDERSCORE ) f( INPUT_KEY_BACKQUOTE, SDLK_BACKQUOTE ) f( INPUT_KEY_A, SDLK_a ) f( INPUT_KEY_B, SDLK_b ) f( INPUT_KEY_C, SDLK_c ) f( INPUT_KEY_D, SDLK_d ) f( INPUT_KEY_E, SDLK_e ) f( INPUT_KEY_F, SDLK_f ) f( INPUT_KEY_G, SDLK_g ) f( INPUT_KEY_H, SDLK_h ) f( INPUT_KEY_I, SDLK_i ) f( INPUT_KEY_J, SDLK_j ) f( INPUT_KEY_K, SDLK_k ) f( INPUT_KEY_L, SDLK_l ) f( INPUT_KEY_M, SDLK_m ) f( INPUT_KEY_N, SDLK_n ) f( INPUT_KEY_O, SDLK_o ) f( INPUT_KEY_P, SDLK_p ) f( INPUT_KEY_Q, SDLK_q ) f( INPUT_KEY_R, SDLK_r ) f( INPUT_KEY_S, SDLK_s ) f( INPUT_KEY_T, SDLK_t ) f( INPUT_KEY_U, SDLK_u ) f( INPUT_KEY_V, SDLK_v ) f( INPUT_KEY_W, SDLK_w ) f( INPUT_KEY_X, SDLK_x ) f( INPUT_KEY_Y, SDLK_y ) f( INPUT_KEY_Z, SDLK_z ) f( INPUT_KEY_DELETE, SDLK_DELETE ) 

#define INPUT_CLICK 127

#endif /* SDLI_H */

